/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type PartnerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "partner";
};

export type AboutContent = {
  _id: string;
  _type: "aboutContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  founding?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  stats?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  values?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  team?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  partners?: Array<
    {
      _key: string;
    } & PartnerReference
  >;
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type HomeContent = {
  _id: string;
  _type: "homeContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: string;
  heroLede?: string;
  featuredEvent?: EventReference;
  quote?: {
    text?: string;
    attribution?: PersonReference;
  };
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  supportUrl?: string;
  email?: string;
  instagramUrl?: string;
  linkedinUrl?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type MediaItem = {
  _id: string;
  _type: "mediaItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
  format: "Video" | "Interview" | "Debate" | "Panel" | "Photo series";
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  topic?: TopicReference;
  people?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  publishedAt: string;
  durationLabel?: string;
  url?: string;
  featured?: boolean;
  relatedEvent?: EventReference;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  author?: PersonReference;
  topic?: TopicReference;
  format?: "Recap" | "Opinion" | "Announcement" | "Interview";
  publishedAt: string;
  standfirst?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  readingMinutes?: number;
  featured?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        text?: string;
        attribution?: PersonReference;
        _type: "pullquote";
        _key: string;
      }
  >;
  relatedEvent?: EventReference;
};

export type VenueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "venue";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  topic?: TopicReference;
  format?: "Dialogue" | "Policy" | "Debate" | "Panel" | "Interview";
  startsAt: string;
  endsAt?: string;
  venue?: VenueReference;
  speakers?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  standfirst?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  registrationUrl?: string;
  entryNote?: string;
  recapUrl?: string;
  recapType?: "video" | "text";
  isCommunity?: boolean;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  addressLine?: string;
  city?: string;
};

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug?: Slug;
  role?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  isCutout?: boolean;
  isTeam?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PersonReference
  | PartnerReference
  | AboutContent
  | EventReference
  | HomeContent
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | TopicReference
  | MediaItem
  | Slug
  | Article
  | VenueReference
  | Event
  | Partner
  | Venue
  | Topic
  | Person
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: {  "home": *[_type == "homeContent"][0]{    heroHeading, heroLede,    quote{ text, attribution->{name, role} },    featuredEvent->{ _id, title, slug, startsAt, "topic": topic->title, coverImage, "venue": venue->name }  },  "upcoming": *[_type == "event" && !isCommunity && startsAt >= $now] | order(startsAt asc)[0...3]{    _id, title, slug, startsAt, "topic": topic->title, format, coverImage,    "venue": venue->name  },  "latestNews": *[_type == "article"] | order(publishedAt desc)[0...3]{    _id, title, slug, publishedAt, standfirst, "topic": topic->title, format, coverImage  },  "media": *[_type == "mediaItem"] | order(publishedAt desc)[0...5]{    _id, title, slug, format, thumbnail, durationLabel, url  }}
export type HOME_QUERY_RESULT = {
  home: {
    heroHeading: string | null;
    heroLede: string | null;
    quote: {
      text: string | null;
      attribution: {
        name: string;
        role: string | null;
      } | null;
    } | null;
    featuredEvent: {
      _id: string;
      title: string;
      slug: Slug;
      startsAt: string;
      topic: string | null;
      coverImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      venue: string | null;
    } | null;
  } | null;
  upcoming: Array<{
    _id: string;
    title: string;
    slug: Slug;
    startsAt: string;
    topic: string | null;
    format: "Debate" | "Dialogue" | "Interview" | "Panel" | "Policy" | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    venue: string | null;
  }>;
  latestNews: Array<{
    _id: string;
    title: string;
    slug: Slug;
    publishedAt: string;
    standfirst: string | null;
    topic: string | null;
    format: "Announcement" | "Interview" | "Opinion" | "Recap" | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
  media: Array<{
    _id: string;
    title: string;
    slug: Slug | null;
    format: "Debate" | "Interview" | "Panel" | "Photo series" | "Video";
    thumbnail: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    durationLabel: string | null;
    url: string | null;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: EVENTS_QUERY
// Query: {  "upcoming": *[_type == "event" && !isCommunity && startsAt >= $now] | order(startsAt asc){    _id, title, slug, startsAt, "topic": topic->title, format, coverImage, "venue": venue->name  },  "past": *[_type == "event" && !isCommunity && startsAt < $now] | order(startsAt desc){    _id, title, slug, startsAt, "topic": topic->title, format, "venue": venue->name, coverImage, recapUrl, recapType  },  "community": *[_type == "event" && isCommunity] | order(startsAt desc)[0...1]{    _id, title, slug  }}
export type EVENTS_QUERY_RESULT = {
  upcoming: Array<{
    _id: string;
    title: string;
    slug: Slug;
    startsAt: string;
    topic: string | null;
    format: "Debate" | "Dialogue" | "Interview" | "Panel" | "Policy" | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    venue: string | null;
  }>;
  past: Array<{
    _id: string;
    title: string;
    slug: Slug;
    startsAt: string;
    topic: string | null;
    format: "Debate" | "Dialogue" | "Interview" | "Panel" | "Policy" | null;
    venue: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    recapUrl: string | null;
    recapType: "text" | "video" | null;
  }>;
  community: Array<{
    _id: string;
    title: string;
    slug: Slug;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: EVENT_BY_SLUG_QUERY
// Query: *[_type == "event" && slug.current == $slug][0]{  _id, title, startsAt, endsAt, entryNote, registrationUrl, recapUrl, recapType, standfirst,  "topic": topic->title, format, coverImage, body,  "venue": venue->{ name, addressLine, city },  "speakers": speakers[]->{ _id, name, role, photo, isCutout },  "related": *[_type == "event" && _id != ^._id && topic._ref == ^.topic._ref] | order(startsAt desc)[0...3]{    _id, title, slug, startsAt, "topic": topic->title, coverImage  }}
export type EVENT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  startsAt: string;
  endsAt: string | null;
  entryNote: string | null;
  registrationUrl: string | null;
  recapUrl: string | null;
  recapType: "text" | "video" | null;
  standfirst: string | null;
  topic: string | null;
  format: "Debate" | "Dialogue" | "Interview" | "Panel" | "Policy" | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  venue: {
    name: string;
    addressLine: string | null;
    city: string | null;
  } | null;
  speakers: Array<{
    _id: string;
    name: string;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    isCutout: boolean | null;
  }> | null;
  related: Array<{
    _id: string;
    title: string;
    slug: Slug;
    startsAt: string;
    topic: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: NEWS_QUERY
// Query: {  "featured": *[_type == "article" && featured == true] | order(publishedAt desc)[0]{    _id, title, slug, standfirst, publishedAt, "topic": topic->title, format, coverImage, readingMinutes,    "author": author->{ name }  },  "articles": *[_type == "article" && (!defined($format) || format == $format)] | order(publishedAt desc)[0...$limit]{    _id, title, slug, publishedAt, standfirst, "topic": topic->title, format, coverImage  },  "total": count(*[_type == "article" && (!defined($format) || format == $format)])}
export type NEWS_QUERY_RESULT = {
  featured: {
    _id: string;
    title: string;
    slug: Slug;
    standfirst: string | null;
    publishedAt: string;
    topic: string | null;
    format: "Announcement" | "Interview" | "Opinion" | "Recap" | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    readingMinutes: number | null;
    author: {
      name: string;
    } | null;
  } | null;
  articles: Array<{
    _id: string;
    title: string;
    slug: Slug;
    publishedAt: string;
    standfirst: string | null;
    topic: string | null;
    format: "Announcement" | "Interview" | "Opinion" | "Recap" | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
  total: number;
};

// Source: ../src/sanity/queries.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{  _id, title, standfirst, publishedAt, readingMinutes, "topic": topic->title, format, coverImage,  "author": author->{ name, role, photo, isCutout, bio },  body[]{ ..., _type == "pullquote" => { text, "attribution": attribution->{name, role} },          _type == "image" => { ..., asset } },  "related": *[_type == "article" && _id != ^._id && topic._ref == ^.topic._ref] | order(publishedAt desc)[0...3]{    _id, title, slug, publishedAt, "topic": topic->title, coverImage  }}
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  standfirst: string | null;
  publishedAt: string;
  readingMinutes: number | null;
  topic: string | null;
  format: "Announcement" | "Interview" | "Opinion" | "Recap" | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  author: {
    name: string;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    isCutout: boolean | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        text: string | null;
        attribution: {
          name: string;
          role: string | null;
        } | null;
        _type: "pullquote";
        _key: string;
      }
  > | null;
  related: Array<{
    _id: string;
    title: string;
    slug: Slug;
    publishedAt: string;
    topic: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: MEDIA_QUERY
// Query: {  "featured": *[_type == "mediaItem" && featured == true] | order(publishedAt desc)[0]{    _id, title, slug, format, thumbnail, durationLabel, url  },  "items": *[_type == "mediaItem"      && (!defined($format) || format == $format)      && (!defined($topic) || topic->slug.current == $topic)    ] | order(        select($sort == "oldest" => publishedAt) asc,        select($sort != "oldest" => publishedAt) desc      ){    _id, title, slug, format, thumbnail, durationLabel, url, publishedAt  },  "topics": *[_type == "topic"] | order(title asc){ _id, title, "slug": slug.current }}
export type MEDIA_QUERY_RESULT = {
  featured: {
    _id: string;
    title: string;
    slug: Slug | null;
    format: "Debate" | "Interview" | "Panel" | "Photo series" | "Video";
    thumbnail: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    durationLabel: string | null;
    url: string | null;
  } | null;
  items: Array<{
    _id: string;
    title: string;
    slug: Slug | null;
    format: "Debate" | "Interview" | "Panel" | "Photo series" | "Video";
    thumbnail: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    durationLabel: string | null;
    url: string | null;
    publishedAt: string;
  }>;
  topics: Array<{
    _id: string;
    title: string;
    slug: string | null;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "aboutContent"][0]{  founding, stats, values,  "team": team[]->{ _id, name, role, photo, isCutout },  "partners": partners[]->{ _id, name, logo, url }}
export type ABOUT_QUERY_RESULT = {
  founding: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  stats: Array<{
    value?: string;
    label?: string;
    _key: string;
  }> | null;
  values: Array<{
    title?: string;
    description?: string;
    _key: string;
  }> | null;
  team: Array<{
    _id: string;
    name: string;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    isCutout: boolean | null;
  }> | null;
  partners: Array<{
    _id: string;
    name: string;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    url: string | null;
  }> | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  title, tagline, supportUrl, email, instagramUrl, linkedinUrl, defaultOgImage}
export type SETTINGS_QUERY_RESULT = {
  title: string | null;
  tagline: string | null;
  supportUrl: string | null;
  email: string | null;
  instagramUrl: string | null;
  linkedinUrl: string | null;
  defaultOgImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: SITEMAP_SLUGS_QUERY
// Query: {  "events": *[_type == "event" && !isCommunity && defined(slug.current)]{    "slug": slug.current, _updatedAt  },  "articles": *[_type == "article" && defined(slug.current)]{    "slug": slug.current, _updatedAt  }}
export type SITEMAP_SLUGS_QUERY_RESULT = {
  events: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  articles: Array<{
    slug: string;
    _updatedAt: string;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "home": *[_type == "homeContent"][0]{\n    heroHeading, heroLede,\n    quote{ text, attribution->{name, role} },\n    featuredEvent->{ _id, title, slug, startsAt, "topic": topic->title, coverImage, "venue": venue->name }\n  },\n  "upcoming": *[_type == "event" && !isCommunity && startsAt >= $now] | order(startsAt asc)[0...3]{\n    _id, title, slug, startsAt, "topic": topic->title, format, coverImage,\n    "venue": venue->name\n  },\n  "latestNews": *[_type == "article"] | order(publishedAt desc)[0...3]{\n    _id, title, slug, publishedAt, standfirst, "topic": topic->title, format, coverImage\n  },\n  "media": *[_type == "mediaItem"] | order(publishedAt desc)[0...5]{\n    _id, title, slug, format, thumbnail, durationLabel, url\n  }\n}': HOME_QUERY_RESULT;
    '{\n  "upcoming": *[_type == "event" && !isCommunity && startsAt >= $now] | order(startsAt asc){\n    _id, title, slug, startsAt, "topic": topic->title, format, coverImage, "venue": venue->name\n  },\n  "past": *[_type == "event" && !isCommunity && startsAt < $now] | order(startsAt desc){\n    _id, title, slug, startsAt, "topic": topic->title, format, "venue": venue->name, coverImage, recapUrl, recapType\n  },\n  "community": *[_type == "event" && isCommunity] | order(startsAt desc)[0...1]{\n    _id, title, slug\n  }\n}': EVENTS_QUERY_RESULT;
    '*[_type == "event" && slug.current == $slug][0]{\n  _id, title, startsAt, endsAt, entryNote, registrationUrl, recapUrl, recapType, standfirst,\n  "topic": topic->title, format, coverImage, body,\n  "venue": venue->{ name, addressLine, city },\n  "speakers": speakers[]->{ _id, name, role, photo, isCutout },\n  "related": *[_type == "event" && _id != ^._id && topic._ref == ^.topic._ref] | order(startsAt desc)[0...3]{\n    _id, title, slug, startsAt, "topic": topic->title, coverImage\n  }\n}': EVENT_BY_SLUG_QUERY_RESULT;
    '{\n  "featured": *[_type == "article" && featured == true] | order(publishedAt desc)[0]{\n    _id, title, slug, standfirst, publishedAt, "topic": topic->title, format, coverImage, readingMinutes,\n    "author": author->{ name }\n  },\n  "articles": *[_type == "article" && (!defined($format) || format == $format)] | order(publishedAt desc)[0...$limit]{\n    _id, title, slug, publishedAt, standfirst, "topic": topic->title, format, coverImage\n  },\n  "total": count(*[_type == "article" && (!defined($format) || format == $format)])\n}': NEWS_QUERY_RESULT;
    '*[_type == "article" && slug.current == $slug][0]{\n  _id, title, standfirst, publishedAt, readingMinutes, "topic": topic->title, format, coverImage,\n  "author": author->{ name, role, photo, isCutout, bio },\n  body[]{ ..., _type == "pullquote" => { text, "attribution": attribution->{name, role} },\n          _type == "image" => { ..., asset } },\n  "related": *[_type == "article" && _id != ^._id && topic._ref == ^.topic._ref] | order(publishedAt desc)[0...3]{\n    _id, title, slug, publishedAt, "topic": topic->title, coverImage\n  }\n}': ARTICLE_BY_SLUG_QUERY_RESULT;
    '{\n  "featured": *[_type == "mediaItem" && featured == true] | order(publishedAt desc)[0]{\n    _id, title, slug, format, thumbnail, durationLabel, url\n  },\n  "items": *[_type == "mediaItem"\n      && (!defined($format) || format == $format)\n      && (!defined($topic) || topic->slug.current == $topic)\n    ] | order(\n        select($sort == "oldest" => publishedAt) asc,\n        select($sort != "oldest" => publishedAt) desc\n      ){\n    _id, title, slug, format, thumbnail, durationLabel, url, publishedAt\n  },\n  "topics": *[_type == "topic"] | order(title asc){ _id, title, "slug": slug.current }\n}': MEDIA_QUERY_RESULT;
    '*[_type == "aboutContent"][0]{\n  founding, stats, values,\n  "team": team[]->{ _id, name, role, photo, isCutout },\n  "partners": partners[]->{ _id, name, logo, url }\n}': ABOUT_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  title, tagline, supportUrl, email, instagramUrl, linkedinUrl, defaultOgImage\n}': SETTINGS_QUERY_RESULT;
    '{\n  "events": *[_type == "event" && !isCommunity && defined(slug.current)]{\n    "slug": slug.current, _updatedAt\n  },\n  "articles": *[_type == "article" && defined(slug.current)]{\n    "slug": slug.current, _updatedAt\n  }\n}': SITEMAP_SLUGS_QUERY_RESULT;
  }
}
